language: go

go:
  - 1.1
  - 1.2
  - tip

services:
  - redis-server

install:
  - go get labix.org/v2/mgo/bson
  - go get menteslibres.net/gosexy/redis

env:
  - GOARCH=amd64

script:
  - go get upper.io/queue
  - go build upper.io/queue
  - go test upper.io/queue
